### ISSUE TITLE
tags posts is null 

### ISSUE THREAD

**Issue by sunapollo** [brokenhandsio/SteamPress#15]
Hi , I have one problem.

`http://localhost:8080/blog/tags/Hello/`
will see `There haven't been any blog posts yet!`

but the Hello tag, have two published posts.

I find 

``` swift
try tag.sortedPosts().all().count 
// is 0 

but 
try tag.posts.all().count
// is two
```

**Comment by 0xTim** [comment]
@sunapollo are the posts published yet? They won't appear under the tag list until the blog posts have been published

**Comment by sunapollo** [comment]
@0xTim Yes I'am sure. the posts published

![image](https://user-images.githubusercontent.com/25025363/27362300-fc1c5714-565f-11e7-87a5-cb8f0075063d.png)

![image](https://user-images.githubusercontent.com/25025363/27362306-0aec637e-5660-11e7-964c-2b3050708760.png)

**Comment by sunapollo** [comment]
@0xTim When I use mysql, it is ok.  but use mongodb is bad.

**Comment by 0xTim** [comment]
Ah so you're saying you only encounter this issue when you use MongoDB? That's odd as everything should be the same from SteamPress's point of view. If you dump the posts and tags tables what do they look like?

**Comment by sunapollo** [comment]
@0xTim on macOS dump the posts and tags, it is ok. but on ubuntu, having MongoKitten.MongoError and when you request `/blog` agin, also have error , view is 500 .

i think that it is maybe MongoKitten Error .

**Comment by 0xTim** [comment]
It does sound like it - I was under the impression that MongoKitten doesn't support Fluent. Might be worth asking in the #mongo channel on Slack

**Comment by sunapollo** [comment]
@0xTim Thinks
