### ISSUE TITLE
user is not login

### ISSUE THREAD

**Issue by sunapollo** [brokenhandsio/SteamPress#16]
When run  `vapor run serve --env=production --release` 
then request `localhost:8080/blog/admin/login` 

input `admin` and password the user is not login.

but run `vapor run`

then user is login

**Comment by 0xTim** [comment]
@sunapollo are you seeing the admin credentials being printed out in the log when you access the login page for the first time?

**Comment by sunapollo** [comment]
```
vapor run serve --env=production --release

Running SteamPressBlog ...
Production mode enabled, disabling informational logs.
Database prepared
Starting server on 0.0.0.0:8080
An Admin user been created for you - the username is admin and the password is vjQUHJwH
You will be asked to change your password once you have logged in, please do this immediately!

```

then input admin and passworld(vjQUHJwH) . not login

**Comment by 0xTim** [comment]
Hmm what OS and DB is this with?

**Comment by sunapollo** [comment]
@0xTim I find that on ubuntu and mac os. using Mysql and find on mongodb is too

**Comment by 0xTim** [comment]
Ok I'll try and reproduce this. Which version of SteamPress is this with?

**Comment by 0xTim** [comment]
@sunapollo just remembered that when running in the production environment it must be run on SSL (it sets the `secure` flag on the login Cookie which only works over HTTPS) and you are accessing localhost so that will be the issue

**Comment by sunapollo** [comment]
@0xTim Thinks. I will try it .

**Comment by sunapollo** [comment]
@0xTim lol you are right . https://dowhile.net/blog/ . it's run success

**Comment by TimC-BBC** [comment]
👍 Nice site too!

**Comment by 0xTim** [comment]
👍 Nice site too!
