### ISSUE TITLE
Title can not chinese

### ISSUE THREAD

**Issue by sunapollo** [brokenhandsio/SteamPress#17]
![image](https://user-images.githubusercontent.com/25025363/27376182-f9080cc8-56a3-11e7-84d8-3e42bc723ad1.png)

when the title is chinese, the url is null

**Comment by 0xTim** [comment]
I'm guessing this is using the Example site's Javascript? You'll need to convert it to punycode but I should do this in the example site as well

**Comment by sunapollo** [comment]
@0xTim Yes，I using the example site's javascript. Thinks 😄

**Comment by 0xTim** [comment]
I'm tracking this in https://github.com/brokenhandsio/SteamPressExample/issues/8 if you're interested - will fix it in the example site

**Comment by sunapollo** [comment]
@0xTim 😄 OK
