### ISSUE TITLE
LeafMarkdown link returns 404 error

### ISSUE THREAD

**Issue by marc-medley** [brokenhandsio/SteamPress#26]
LeafMarkdown (https://github.com/brokenhandsio/LeafMarkdown) references in README.md and Tests/SteamPressTests/Helpers/TestDataBuilder.swift return a 404 page not found error.

Appears that LeafMarkdown repository is gone. … although LeafMarkdown is still referenced in a number of GitHub locations: https://github.com/search?q=LeafMarkdown

**Comment by 0xTim** [comment]
Good spot! LeafMarkdown has been merged back in upstream into the original repository it was forked from - https://github.com/vapor-community/markdown-provider - so take a look at that. I've updated all the references
