### ISSUE TITLE
raw HTML omitted

### ISSUE THREAD

**Issue by 0xPr0xy** [brokenhandsio/SteamPress#30]
I see you include prism.js, but when trying to display highlighted code I get `raw HTML omitted` in the post dom.
Where is this coming from and how do I allow HTML in post

**Comment by 0xPr0xy** [comment]
Update: I found out that with the following markdown notation It seems to work in browser

```
~~~.language-swift
func getGreeting() -> String {
	return "Hello, World!"
}
~~~
```

But this makes the WYSIWYG editor display the code striked through.
Also, still curious how I could get HTML to work since it is trusted input, so raw html does not need to be escaped here.

**Comment by 0xTim** [comment]
@0xPr0xy if you are trying to enter HTML in a post you want to use [Markdown code blocks](https://guides.github.com/features/mastering-markdown/) (see code blocks), so for Swift it would be
```swift
func getGreeting() -> String {
	return "Hello, World!"
}
```

For HTML you want to do
```html
<h1>Hello World!</h1>
```

Does that do what you were looking for?

**Comment by 0xTim** [comment]
😂 Github is formatting my code for me!

**Comment by 0xTim** [comment]
<pre>
```swift
func getGreeting() -> String {
	return "Hello, World!"
}
```
</pre>

and

<pre>
```html
&lt;h1&gt;Hello World&lt;/h1&gt;
```
</pre>

**Comment by 0xTim** [comment]
Or are you trying to write HTML in your posts that will be rendered as HTML when published or write HTML code in your posts that won't get rendered?

**Comment by 0xPr0xy** [comment]
I was trying to use the HTML notation of prism to highlight the swift code, so in essence I was trying to render that html tags to highlight the swift code, markdown works fine though, html rendering is limited I guess

**Comment by 0xPr0xy** [comment]
Oh is it now just ‘’’swift I used ~~~language-swift?

**Comment by 0xTim** [comment]
Ah yeah use <code>```swift</code> (three back ticks) to start and end code blocks and it will generate `<pre><code class="swift">...</code></pre>` which any code highlighting library will work with
