### ISSUE TITLE
Continue Reading link does not work from search result on partial match

### ISSUE THREAD

**Issue by 0xPr0xy** [brokenhandsio/SteamPress#32]
Because it generates this Continue Reading link:
http://localhost:8080/blog/posts/%3Cspan%20class%20=%20'highlight'%3Ehello%3C/span%3E-world/

The span class around the partial match causes this link to result in a not found

**Comment by 0xTim** [comment]
Closing this as its a bug in the Javascript in the Example site so will fix it in brokenhandsio/SteamPressExample#19

**Comment by 0xTim** [comment]
brokenhandsio/SteamPressExample#19 has now been fixed with brokenhandsio/SteamPressExample#20
