### ISSUE TITLE
Not log default admin password when preparation.

### ISSUE THREAD

**Issue by happiness9721** [brokenhandsio/SteamPress#33]
I found out there is a sequence problem with setupProviders.
If I add FluentProvider before add SteamPressProvider, such like
```
private func setupProviders() throws {
    try addProvider(FluentProvider.Provider.self)
    try addProvider(PostgreSQLProvider.Provider.self)
    try addProvider(LeafProvider.Provider.self)
    try addProvider(SteamPress.Provider.self)
  }
```
BlogAdminUser's prepare function will be call before `boot(_ drop: Droplet)` (log is set there).
So the log will not show when preparation.

Maybe we could change log?.error() to print() or note this in the markdown file?

**Comment by 0xTim** [comment]
Ah yeah that would happen, hopefully this will be improved in Vapor 3 - I'll update the README, thanks!
