### ISSUE TITLE
Vapor has been upgraded to 3.0

### ISSUE THREAD

**Issue by VineFiner** [brokenhandsio/SteamPress#37]
When is the official version released?

**Comment by 0xTim** [comment]
@VineFiner there is a `vapor3` branch that I'm currently doing the port on. I'm also waiting on Fluent, Auth and Leaf to be tagged and released

**Comment by VineFiner** [comment]
OK,Thank you.

**Comment by 0xTim** [comment]
Reopening this, will close it once Vapor 3 is supported!

**Comment by majortom64** [comment]
Any word on the Vapor 3 version?

**Comment by acche** [comment]
Expecting Vapor 3 version release.

**Comment by InukVT** [comment]
Anything I can do to be of assistance?

**Comment by majortom64** [comment]
Should we assume this project is dead? :-(

**Comment by 0xTim** [comment]
@majortom64 absolutely not! 😃 

The PR is [here](https://github.com/brokenhandsio/SteamPress/pull/36) and I've pushed around a hundred commits in the last couple of weeks. I basically have one more file to implement before I tag the first alpha and start trying it out!

**Comment by 0xTim** [comment]
PR is _finally_ merged, now ready to start integration testing and seeing if it all works!
