### ISSUE TITLE
Server error: dispatch(HTTP.ParserError.invalidStartLine)

### ISSUE THREAD

**Issue by douglance** [brokenhandsio/SteamPress#4]
Upon installing example project, We are seeing this  error when trying to login the first time: 

`Server error: dispatch(HTTP.ParserError.invalidStartLine)
`

**Comment by 0xTim** [comment]
Hi @douglance are you running the SteamPressExample page with the engine as well? What OS are you experiencing the issue on and are you running straight Vapor or are you running it behind a proxy (like Nginx)? I haven't seen this issue at all I must admit (sounds like it could be a Vapor issue, though more detail will help diagnose)

**Comment by 0xTim** [comment]
Also what version of Vapor are you pulling in?

**Comment by 0xTim** [comment]
https://github.com/miswift/miswiftdotcom/blob/mailchimp/Package.swift

Is this your `Package.swift` that you are using? If so you need to update to Vapor 1.5

**Comment by douglance** [comment]
Good call! Thank you!

**Comment by douglance** [comment]
Actually, with the new Vapor version, I'm still receiving the same error and pages take an awful long time to load. It hangs on establishing a secure connection.

**Comment by 0xTim** [comment]
Have you tried a different browser? And are you running the VaporSecuityHeaders browser? I had an issue where it refused to load a CSS file in Safari but restarted the browser and the app and it all seemed fine

**Comment by 0xTim** [comment]
PS If you have used the Example site, that has a Content Security Policy to block non HTTPS requests, so if running locally your CSS download will just hang. The latest code on the example site on `master` has a fix for this

**Comment by 0xTim** [comment]
@douglance are you still having issues? Will close this issue if not

**Comment by decisiveweb** [comment]
I cloned a copy of the Example Site, built it and ran it as a local host.  It now appears to be working fine.  I get the login and password on the terminal page.  I am able to log in.  It requires a new login password.  I was able to make a new blog post.  I believe this supports closing this issue
